---
- name: update apt cache
  apt:
    update_cache: true
  changed_when: false

- block:
    - name: install the python sni support packages
      package:
        name: "{{ docker_python_sni_pip_dependencies }}"
        state: present

    # There extra pip dependencies are needed to add SSL SNI support to
    # Python version prior to 2.7.9. SNI support is needed by the Ansible
    # apt_key module.
    - name: Install the Python SNI python-pip dependencies.
      pip:
        name: "{{ docker_python_sni_pip_dependencies }}"
        state: present
  when: ansible_python_version is version_compare('2.6.0', '>=')
    and
    ansible_python_version is version_compare('2.7.9', '<')

- name: install apt-transport-https and gnupg if necessary
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present

- name: import docker apt public key
  apt_key:
    url: "{{ docker_repo['apt_gpg_key'] }}"
    id: "{{ docker_repo['apt_gpg_key_id'] | default('') }}"
    state: present

- name: add the docker apt repository
  apt_repository:
    repo: "{{ docker_repo['apt_repo'] }}"
    filename: "{{ docker_repo['name'] }}"
    state: present
