---
- name: Prefix docker cli package version
  when:
    - docker_cli_package_version | length > 0
  block:
    - name: Prefix the docker cli package version with the correct separator on redhat
      when:
        - ansible_os_family == 'RedHat'
      ansible.builtin.set_fact:
        _docker_cli_package_version: "-{{ docker_cli_package_version }}"

    - name: Prefix the docker cli package version with the correct separator on debian
      when:
        - ansible_os_family == 'Debian'
      ansible.builtin.set_fact:
        _docker_cli_package_version: "={{ docker_cli_package_version }}"

- name: Install the docker cli
  ansible.builtin.package:
    name: "{{ docker_cli_package_name }}{{ _docker_cli_package_version | default('') }}"
    state: "{{ docker_cli_package_state }}"
