---

- name: Install epel-release
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
  become: true
  ansible.builtin.package:
    name: "epel-release"
    state: present

- name: Install python-pip
  become: true
  ansible.builtin.package:
    name: "{{ docker_python_pip_packages }}"
    state: present
