---
- name: Prefix docker package version
  when:
    - docker_package_version | length > 0
  block:
    - name: Prefix the docker package version with the correct separator on redhat
      when:
        - ansible_os_family == 'RedHat'
      ansible.builtin.set_fact:
        _docker_package_version: "-{{ docker_package_version }}"

    - name: Prefix the docker package version with the correct separator on debian
      when:
        - ansible_os_family == 'Debian'
      ansible.builtin.set_fact:
        _docker_package_version: "={{ docker_package_version }}"

- name: Install docker
  become: true
  ansible.builtin.package:
    name: "{{ docker_package_name }}{{ _docker_package_version | default('') }}"
    state: "{{ docker_package_state }}"
