---

- name: Install docker-engine
  when: docker_deploy_action == "install"
  block:
    - name: Install the docker repository
      ansible.builtin.include_tasks:
        file: "tasks/sub-tasks/repo-{{ ansible_os_family }}.yml"
      when: not docker_engine_skip_repo

    - name: Install python-pip
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup-python-pip.yml

    - name: Install docker dependencies
      ansible.builtin.package:
        name: "{{ docker_dependencies }}"
        state: present
      when: not docker_engine_skip_containerd
            or
            not docker_engine_skip_engine

    - name: Install containerd
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup-containerd.yml
      when: not docker_engine_skip_containerd

    - name: Install the docker engine
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup-docker-engine.yml
      when: not docker_engine_skip_engine

    - name: Install the docker cli
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup-docker-cli.yml
      when: not docker_engine_skip_cli

    - name: Add the docker admin users to the docker group
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup-docker-group.yml
      when: not docker_engine_skip_group

    - name: Install docker-py
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/setup-docker-py.yml
      when: not docker_engine_skip_docker_py


- name: Remove docker-engine
  when: docker_deploy_action == "uninstall"
  block:
    - name: Remove docker engine
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ docker_package_name }}"
        - "{{ docker_cli_package_name }}"
        - "{{ containerd_package_name }}"

    - name: Remove group
      ansible.builtin.group:
        name: "{{ docker_group_name }}"
        state: absent
